//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektOI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Visits = new HashSet<Visit>();
        }
    
        public int IDDoctor { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public int IDSpecialisation { get; set; }
        public System.TimeSpan WorkStart { get; set; }
        public System.TimeSpan WorkEnd { get; set; }
    
        public virtual Specialisation Specialisation { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
