//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektOI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int IdVisit { get; set; }
        public int IDPatient { get; set; }
        public int IDDoctor { get; set; }
        public int IdReceptionist { get; set; }
        public System.DateTime VisitDate { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Receptionist Receptionist { get; set; }
    }
}
